module.exports = [
  "Autamme yrityksiä tunnistamaan ja ymmärtämään digitalisoitumiseen liittyviä mahdollisuuksia.",
  "Rakennamme enemmän ja parempaa liiketoimintaa vähemmällä verkkoa ja sen mahdollisuuksia hyödyntäen.",
  "Synnytämme visioita, ymmärrystä, suunnitelmia, valmiita palveluita ja parempaa markkinointia.",
  "Elämme kuten opetamme.",
  "Emme väitä vaan näytämme.",
  "Jakaminen on välittämistä.",
  "Suunnittelen strategioita, monikanavaista markkinointiviestintää, tuotteita ja palveluita.",
  "Olen työskennellyt yli viisitoista vuotta markkinointiviestinnän parissa ja sinä aikana olen suunnitellut kaikkea merkeistä yritysilmeisiin, tuotteista palveluihin, analogisesta digitaaliseen ja monologista dialogiin.",
  "Bloggaan markkinointiviestinnän murroksesta ja haasteista.",
  "Työkseen hän tutkii, havainnoi ja hyödyntää digitaalisia kanavia ja sosiaalista mediaa asiakkaidensa liiketoiminnan hyväksi.",
  "Rakentaa tulevaisuuden tarinaa.",
  "Laittaa itsensä likoon ja välittää aidosti.",
  "Ideoi uutta.",
  "Vahva 15 vuoden myynti- ja digitutkimustausta.",
  "Auttaminen on parasta markkinointia.",
  "Sisältöstrategi, sisältömarkkinoija ja tarinankertoja.",
  "Digitaalisen median ammattilainen, bloggaaja ja vespailija.",
  "Kiinnostunut tulevaisuuden rakentamisesta ja digitaalisesta maailmasta.",
  "Tutkii uteliaana kaikkea journalistisin silmin.",
  "Auttaa asiakkaita kommunikoimaan paremmin oikeanlaisten sisältöjen ja tarinoiden avulla, koska tarinat myyvät ja vaikuttavat parhaiten.",
  "Vimmaisia ajatuksia ja lapsenomaista intoilua.",
  "Markkinointia, mainontaa, tarinankerrontaa ja tekoja. Propellipää ja pilkunviilaaja, luottopakki ja ikiliikkuja.",
  "Ei koskaan kylläinen.",
  "Koodasin Basicilla '87, rakensin saitin Notepadilla '97.",
  "Kasvoin aikuiseksi ja kyllästyin digiin digin vuoksi. Nyt käyntikortissa lukee Copywriter.",
  "Kirjoittaa, puhuu ja tekee.",
  "Ensimmäisen polven rivimaisteri, sosiaalisen median ja digitaalisen viestinnän asiantuntija sekä siirtolapuutarhuri.",
  "Intohimona suklaa, espresso ja laadukas sisältö.",
  "Kivimiesten kaveri.",
  "##NAME## Jatkuvan tekemisen ja kehittämisen fani.",
  "Suunnittelija, tuottaja, kirjoittaja, ohjaaja, johtaja ja myyjä.",
  "##NAME## uskoo, että parhaiten pärjäävät ne yritykset, jotka palvelevat ensin asiakkaitaan ja vasta sitten osakkeenomistajiaan.",
  "Diginatiivi ja kyseenalaistaja, ##NAME## haluaa tehdä maailmasta paremman paikan niin itselleen, lapsilleen kuin muillekin ihmisille.",
  "Social media, social TV, communities, digital marketing, media & content, mindfulness and living from the heart.",
  "Freelancer, social media consultant and mindfulness coach.",
  "Oivallutan B2B-yrityksiä, organisaatioita ja järjestöjä kohti parempaa markkinointia ja yritysivestintää.",
  "Minulla on kokemusta myös ketterien digitaalisten palveluiden johtamisesta, konsultoinnista ja myynnistä.",
  "Entisessä elämässään ammattiurheilija ja maailmanmestari, joka tietää, että loistava tiimi pystyy mihin vain.",
  "Media and ICT serial entrepreneur.",
  "Speaker.",
  "Digital Marketing Evangelist.",
  "Luomme sisältöä, jaamme sen oikeissa kanavissa ja optimoimme parempien tulosten saavuttamiseksi.",
  "M.Sc. Social Psychology.",
  "Ajatteleva puhuja, toisinaan myös puhuva ajattelija.",
  "Kyseenalaistaja, uudistuksen sanansaattaja, tyhmyyden poistaja.",
  "Kirjoittava ja liikkuva.",
  "Mustavalkokuvaaja.",
  "Asemapaikkana Pirkanmaa, työmaana Suomi.",
  "Kuntaprosessien sähköistäjä.",
  "Bisneksen kehittäjä.",
  "Musiikin suurkuluttaja.",
  "Avantomies.",
  "##NAME## on toisen polven asiantuntijayrittäjä ja ex-nokialainen.",
  "Uudistunut asiantuntija joka puhuu IT:tä Businekselle.",
  "Hän pitää avoimuutta ja jakamista pelastajana.",
  "Sosiaalinen media on hänelle elämäntapa.",
  "We create better workday experiences so you could offer better customer experiences to your customers.",
  "Insight- ja kuluttajaymmärryksen asiantuntija.",
  "Brändeistä, mediasta ja populaarimusiikin tähteydestä väitetellyt FT.",
  "Now doing what I love most: building a digital business out of a consumer service.",
  "It takes a multi-disciplined approach, hands-on work with the UX demands and enough smarts and guts to push change through the organization.",
  "The result: global reach and competitive advantage on the world stage.",
  "Anything less seems too ordinary.",
  "LinkedIn & Pinterest specialist and crowdsourcing enthusiast.",
  "16+ years with social media startups with stints at global bluechips in between.",
  "##NAME## työskentelee sisältömarkkinointivelhona vastuullaan sisältöstrategia sekä koukuttavan sisällön tuottaminen.",
  "Hän haluaa olla mukana luomassa parempaa sisältömarkkinointia, joka ilahduttaa ja oivalluttaa asiakkaita.",
  "Strateginen ajattelu, vaikuttaminen ja kädet mullassa tekeminen.",
  "Siitä on osaamiseni tehty.",
  "Yrittäjyys ja digitalisoitumisen mahdollisuudet inspiroivat aina.",
  "Ja hyvä keskustelu! I believe in marketing.",
  "I believe in great brands.",
  "Marketing entrepreneur, blogger, reader, learner.",
  "Marketing used to be easy.",
  "One had only a few to pick from.",
  "TV, radio, or print.",
  "Then came the internet and changed everything.",
  "Now one has to be writer, editor, photographer, SEO optimizer, and so on to be a marketer.",
  "There's no Da Vinci in the modern marketing.",
  "Marketing is more than ever a team effort.",
  "Both internally in the company and as a outsourced service.",
  "In the upcoming years we are going to see a major shift to outsourcing marketing.",
  "Companies don't have enough time to learn the new essential skills required doing modern marketing.",
  "Companies don't want to employ more people.",
  "Outsourcing becomes a safer solution.",
  "##NAME## on analyyttinen sisältöstrategi joka suunnittelee ja tekee asiakkaan asiakkaisiin vaikuttavaa markkinointia.",
  "Positiivinen innostuja ja ihmettelijä, yhdistelmä humanistia ja nörttiä.",
  "Juuri nyt ajankohtaista: yhteisöllisten kulttuurien luominen ja markkinointiautomaatio.",
  "Helping Finnish brands grow international.",
  "Elää tiedosta ja tiedolla johtamisesta.",
  "Suorasanaista keskusteluseuraa kaikesta tietoon ja sen hyödyntämiseen liittyvästä.",
  "Lähimpänä sydäntä datascience, analytiikka ja bigdata.",
  "If you want to spice up your brand and marketing, don't hesitate to get in touch.",
  "Organisaatioanarkisti, rakkauden ammattilainen.",
  "Analogisti digipöh(i)nässä.",
  "AD, creative director, story teller I'm a creative mind who is capable of constantly producing new and fresh ideas.",
  "#Digitalist by nature, copywriter at heart.",
  "Always seeking for a fresh point of view.",
  "A strong believer of team work.",
  "A passion for demystifying business digitalization.",
  "Applying new technology to improve business efficiency and enable new business models.",
  "Miten saavuttaa avainyleisöt sisäisesti ja ulkoisesti? Miten viestiä mahtavista asioista? Miten tuottaa ja toimittaa arvoa? Muun muassa näitä mietin.",
  "Itseni ja ympäristöni kehittäminen sekä johtaminen ovat intohimoni.",
  "Ja paljon muuta.",
  "##NAME## kannustaa yrityksiä rakentamaan kilpailuetua mielipidejohtajuudella ja tekemään markkinoinnista aidosti palvelua.",
  "Mobiili moniyrittäjä (Nomadityöntekijä).",
  "Kehitämme verkostomaisia malleja organisaatioiden digitalisoitumisen edistämiseen ja autamme yrityksiä löytämään sopivat kumppanit kehityshankkeissa.",
  "Yrityssparraaja, Suomen ainoa yksityinen yritysneuvoja.",
  "Intohimoina myynti ja markkinointi, etenkin sosiaalinen media ja it-asiat kaikkinensa.",
  "##NAME## on enemmän kuin kala vedessä erityisesti pienyrittäjäkentällä, johon yksi hänen yrityksistään palveluita tuottaakin.",
  "##NAME## sanoo asiat ääneen, nekin mitä useimmat eivät uskalla.",
  "Kuitenkin konstailematta selkeällä suomenkielellä.",
  "Tahto muuttaa maailmaa yrittäjäystävällisemmäksi, yhdessä! Yrittäjän Päänä ja olkapäänä.",
  "Avainsanoja: strateginen sisältö, tunteet, markkinointiviestintä, ilmiöt, kulttuuri.",
  "I have been working in managing positions in e-commerce business over nine years.",
  "During that time the whole industry has changed radically.",
  "Hence even whole consumer business has changed.",
  "It is a fine art of being able to keep yourself on the top of the wave, which requires a lot of vision and testing.",
  "One simple test might be more valuable than tens of hours in meeting room.",
  "I have passion for leadership.",
  "The passion leads to personal development, therefore I am focusing to improve my leadership skillset constantly.",
  "I am a lifelong learner.",
  "I truly believe that oneself should be able to critically evaluate themselves and improve their self awarerness to be able to be a better leader.",
  "The world around us is rapidly changing, therefore leaders are required to enable themselves in constant self development.",
  "Moreover one must have a true passion for what ever one is doing to succeed.",
  "I'm on a mission to disrupt traditional thinking and models in business world.",
  "By combaining techology and user experience, we can provide phenomenal service for customers, who ever they are, at anytime or place.",
  "Hence, one could argue me to be UX/CX enthusiast.",
  'I am interested in drone delivery, electric cars (and airplanes), solar power, IoT and other "breaktrough tech.',
  "Everything what changes the world to better place, fascinates me.",
  "Digitalisoitumisen muutosagentti, liiketoimintakonsultti ja projektipäällikkö, jonka ajattelu rakentuu asiakaskokemuksen optimoinnin ympärille.",
  "##NAME## on iloinen työmyyrä ja intohimoinen uuden oppija, joka vannoo turhan työn poistamisen ja ketterien menetelmien nimeen.",
  "Minulla on luja usko ihmisiin ja fiksuihin organisaatioihin.",
  "Chef, dad and husband at home.",
  "##NAME## on on media-alan yrittäjä.",
  "##NAME## on San Franciscossa työskentelevä viestinnän ammattilainen, joka auttaa teknologiayrityksiä menestymään digitaaliseen viestintään ja markkinointiin liittyvien ratkaisujen avulla.",
  "Brand and marketing strategist focused on creating growth and increased effectiveness and profitability.",
  "Changing the way we change! Consultant and evangelist of modern information work.",
  "Experienced business process consultant, especially in terms of linking business goals to information workers' daily operations.",
  "For organizations and ecosystems digitalization means cutting out process loss and non-valuable work.",
  "For employee it means understanding how business transactions are connected to networked communnications.",
  "##NAME## is a new-age marketing professional with enthusiastic attitude, drive and curios mind.",
  "Täydellä sydämellä ja ilolla mukana kaikessa.",
  "Serial intrapreneur ja mustan vyön fasilitaattori.",
  "Tutkalla tällä hetkellä mm API-talous ja kognitiivinen tietojenkäsittely.",
  '##NAME## on ennen kaikkea tavoitteellisen bloggaamisen sanansaattaja, "entäs sitten?" -kyseenalaistaja ja konkreettisten vinkkien ylin ystävä, jolla on työntekijälähettilyys lähellä sydäntään.',
  "I'm a Marketing Passionista who believes in making a difference through authenticity and empathy.",
  "Extensive over 15 years of experience from developing and enforcing customer centricity across industries from customer insight and analytics to customer strategies, processes competencies and culture.",
  "Focusing currently on enabling companies in marketing and sales transformation, multi-channel business, and using advanced analytics across business processes from sales and marketing to service, supply chain and risk management related processes.",
  "##NAME## on markkinointimies ja vuokrajohtaja.",
  "Intohimoinen kamppailulajien harrastaja, joka rakastaa myös balettia.",
  'Idearikas toteuttaja, jonka arvolupaus onkin: "saan markkinointisi toimimaan tai saat rahasi takaisin".',
  "##NAME## is a global-minded person with an analytical mindset and a great set of soft & quantitative skills.",
  "Graffaa, typografiaa, t-paitoja, ilmeitä, konsepteja ja verkkopalveluita.",
  "Digitalisti ja harrastaa valon kuvaamista.",
  "Olen digitaalisen markkinoinnin arkkitehti.",
  "Sisältömarkkinoija, strategi ja bloggaaja.",
  "Uskon että yritysten strateginen kilpailuetu syntyy onnistuneen myynnin ja markkinoinnin, asiakaskokemuksen sekä designen kautta.",
  "All about #Innovation, #ThinkDifferent, #Digital, #Ads, #Entrepreneur, #ThreeKids, #Helsinki Digital strategist driven by all things new.",
  "Tietokirjailija, TV-juontaja, muutosvalmentaja, muotoilija ja puhuja.",
  "Intohimot: inspiraatio, osallistaminen, kirjoittaminen, visualisointi ja yhdessä paremman maailman luominen.",
  "Digimarkkinoinnin Neuvonantaja.",
  "Arvopohjaisen Markkinoinnin Suunnannäyttäjä.",
  "Speakersforum Jäsen.",
  "Rakentanut Digimarkkinointikehyksen eri alojen gurjen periaateoppien pohjalle.",
  "Tj, yrittäjä, konsultti, tietokirjailija.",
  "Kantaa huolta erityisesti perinteisestä PK-sektorista sekä julkisista organisaatioista ja niiden toimintakyvyn edistämisestä.",
  "Yritys tekee töitä uuden ajattelun, modernien toimintamallien ja vereksen toimintakulttuurin luomiseksi.",
  "Mukana kulkee mittava työkalupakki.",
  "Tanakka yhdistelmä teoriaa ja käytäntöä.",
  "Tausta suomalaisissa ja ulkomaisissa markkinointitoimistoissa copyna, luovana johtajana ja omistajana.",
  "Palkittu töillään meillä ja maailmalla.",
  "Sanoo integraation olevan elämäntehtävä.",
  'Sales and Branding Guru in whom the persistence and strength of a Rottweiler meets the wisdom of Obi Wan Kenobi." Autan yrittäjiä tekemään enemmän myyntiä verkossa.',
  "Hermostuu siinä vaiheessa palaveria kun irtikset alkavat lentämään.",
  "I am an eternal business developer.",
  "I am passionately enthusiastic about brands, company cultures and customer economics: How to turn companies from product- and production centric around to be customer driven, to create great customer experience.",
  "What it means to company culture, to company structures, to every employee, to management.",
  "And equally enthusiastic about digitalization: how to build great user experience, how to combine them with physical world as a part of service ecosystem, what it means when you open up your company for customers.",
  "Has worked in various political positions as an elected member.",
  "Is a firm believer of opportunities.",
  "Luonnollisesti myös vapaa-ajalla vietän runsaasti aikaa Somen syövereissä.",
  "Y-sukupolven edustaja, joka on sisällä milleniaalien ja Z-sukupolven maailmassa ammentaen sieltä oppia asiakkaidensa auttamiseksi.",
  "Mielenkiinnon kohteita ovat toimivien ratkaisuiden ja toimintamallien hyödynnettävyys eri toimialoilla, viimeisin teknologia ja sen tuomat mahdollisuudet sekä organisaatioiden sparraus tämän kaiken käyttöönotossa.",
  "Digi-Suomen rakentaja, joka uskoo suomalaisen ohjelmisto-osaamisen olevan merkittävässä roolissa hyvinvointiyhteiskuntamme pelastamisessa - kunhan vain päätämme tehdä hommat fiksusti itse.",
  "Haluaa olla omalta osaltaan varmistamassa, että digitalisaatio näkyy suomalaisten yritysten parantuneena kilpailukykynä kansainvälisillä pelikentillä ja että sen myötä koko Suomen hyvinvointi lisääntyy.",
  "Nautin asioiden tekemisestä itseäni fiksumpien kanssa.",
  "She trains companies, associations and organizations to use social media strategically and with a thought.",
  "Her company also offers companies possibilities to outsource social media strategy, planning and content creation.",
  "Disciplined UX craftsman & no-nonsense transformation strategist with an extra flavour of your local car dealer sales guy attitude.",
  "My inspiration comes from delivering the understanding and tangible solutions for the (infinite) value of experience.",
  "Experienced in marketing, passionate about the change disruptive technologies bring to businesses.",
  "The company is redefining how audio is ordered, produced, and used in the creative industries.",
  "Happy and smiley most the time.",
  "Käyttäjäkokemuksen Martin Riggs.",
  "Avainsana: UX.",
  "Kiinnostuksen kohteena työtavat ja niiden muutos, motivaatio, itsensä johtaminen, jatkuva oppiminen sekä digitalisaatio.",
  "Mottona Never Stop Learning ja tavoitteena parempi maailma.",
  "M.sc in information technology with a studies and solid knowledge of writing and digital marketing & branding.",
  "Helped many companies and individual as well as company leaders to brand themselves better with success.",
  "Living in Tampere, helping customers in all over Finland, hopefully in the near future also in some other countries.",
  "Entinen yrittäjä ja koulutukseltaan yht.maist., MBA, tiedottaja sekä Johdon ja esimiesten työnohjaaja.",
  "User experience and user-centered design professional with background in industrial design.",
  "Doctoral degree (Doctor of Arts) from University of Art and Design.",
  "Over 20 years of experience on the field in specialist and managerial roles.",
  "Specialties: User experience processes and management, user-centered design of products and services.",
  "##NAME## is a passionate advocate for innovation, digital business and building winning teams.",
  "He is a sales and marketing professional, known for his positivity, never-give-up attitude and unlimited creativity.",
  "##NAME## has over 17 years of experience in building and managing successful international sales organizations in the IT industry.",
  "Super-optimistic and energetic, he is always looking for new ways to inspire and engage people.",
  "##NAME## enjoys reading, skiing, sailing and jogging as well as creating new business concepts and innovations.",
  "Kiinnostuksen kohteina digitaaliset strategiat, myynti ja kehityksen kehittyminen.",
  "Storyteller.",
  "Author.",
  "Leader.",
  "I enjoy helping our customers find the best business opportunities for their field of operations and guide them on their path to digital business growth.",
  "To me the best brands are the best stories - the ones that connect with a human insight.",
  "Success to me lies in tapping into a story easy enough to tell forward.",
  "If the key account is not telling my story to customer in effective way, or the consumer is not recommending the product to their friends, I have not managed to tell my story right.",
  "Tailoring the message to different audiences has made it possible to manage a vision shared with the management, and delivered excellent business results.",
  "Pitkän linjan digitekijä ja kokenut tuotteistaja, joka näkee enemmän mahdollisuuksia kuin ongelmia.",
  "Nopeasykkeisen päivätyön vastapainoksi harrastan pitkiä kirjankirjoitusprojekteja.",
  "Opiskelen samalla kyberturvallisuutta.",
  "##NAME## on utelias ja kokeilee mielellään uusia asioita.",
  "##NAME## on erityisen kiinnostunut digitaalisesta transformaatiosta, visuaalisesta johtamisesta, palvelumuotoiluilusta ja pelillistämisestä.",
  "Datadiggari joka on saanut osallistua usean eri toimialan ongelmakenttiin.",
  "At the moment excited about analytics, big data, e-commerce and digital media solutions.",
  "Maailman muuttumisesta innostunut viestintäyrittäjä.",
  "Kielen ja digitaalisen median ammattilainen, joka etsii uusia tarinoita ja tarttuu puheenaiheisiin.",
  "I believe that everything between a brand and consumer is media and we all should be constantly looking for new innovative ways for brands to connect with their audience.",
  "I have a versatile background from media, sales and marketing roles.",
  "In other words you could say that I started by selling media, then moved on to buy media and now I'm creating content for media.",
  "Autan organisaatioita hyödyntämään kehittynyttä data-analytiikkaa - strategiasta osaamisen kehittämiseen ja lopulta analytiikkaratkaisujen toteutukseen saakka.",
  "Content Specialist ja digiguru, kirjoittaja on pitkän linjan markkinointi-, media- ja digialan ammattilainen.",
  "Kyyninen paska, mutta aina valmis kokeilemaan uutta ja erilaista.",
  "Sanoo asiat suoraan niin asiakkaille kuin työtovereillenkin.",
  "Vapaa-aikanaan häiritsee kunnollisia kansalaisia erinäköisillä instrumenteilla ja/tai huutamalla sävelestä.",
  "Nuori, naiivi ja energinen sarjayrittäjä.",
  "Kiinnostunut teknologioista ja siitä kuinka digitalisoituminen voi parantaa meidän jokaisen arkea.",
  "Vallitsevan ajattelun harhoista luopuja.",
  "Yrittäjä – ei osaa muullakaan tavalla.",
  "Palkkatyönä tietotekniikkaa ensimmäisessä polvessa.",
  "Tavoitteena muuttaa maailmaa - ei tiedä tarkalleen miten.",
  "Finish it - there is no excuse! Sarjayrittäjä, luennoitsija, tutkija, konsultti ja tietokirjailija.",
  "Hänen ydinosaamista ovat digitalisaatio, digitaalisten liiketoimintamallien, ekosysteemien, työidentiteetin ja ketterän johtamisen kehittäminen.",
  "##NAME## on perustanut viisi yritystä ja sparrannut yli 100 liikeideaa ja uutta palvelua TOP100-yrityksille sekä pk-yrityksille että aloittaville teknologiayrityksille.",
  "Key Skills: •Sales and Business Development •Leadership •Training and Development •Strategic Problem Solving and Planning •Communication •Technical: MS Office; Webshop Solutions; ERP; e-Commerce; Digital Marketing & Services; Google Analytics 6 adwords",
  "Aikaisemmin vastannut sosiaaliseen mediaan erikoistuneen Somecon Helsingin liiketoiminnasta ja kehittänyt johtavana konsulttina asiakasyritystensä asiakaspalvelua ja -viestintää verkossa.",
  "Erikoistunut tietoverkoissa käytävään reaaliaikaiseen vuorovaikutukseen, brändin rakentamiseen, sisältökonsepteihin ja strategioihin.",
  "Vapaa-aika kuluu musiikin, eräjormailun tai ruoan parissa ja sen kyllä huomaa.",
  "Olen monitoimikone pk-yrityksille, jotka haluavat saada lisää asiakkaita netistä.",
  "Eli joo, oon aikamoinen geek.",
  "##NAME## uskoo, että useimmat yritykset mittaavat menestyksensä edelleen euroilla ja vain kaupallisella asiakaskokemuksella on merkitystä.",
  "Startup-höyrähtänyt HR, joka viihtyy kun vauhti on kovaa.",
  "Arvojen ja yrityskulttuurin kätilö.",
  "Rohkeuden, oppimisen ja vapauden puolestapuhuja.",
  "Be Brave.",
  "Keep Learning.",
  "Feel Free.",
  "Life is here, now.",
  "Yesterday was already, tomorrow is not here yet.",
  "Living in now, helping others to learn these skills.",
  "To gain more happiness, balance, focused mind, health, thrive, creativity......",
  "Mindfulness -counselor.",
  "Special interest - mindfulness at work.",
  "Occupational Health Nurse with knowledge and experience in preventing various occupational health risk and supporting health at work.",
  "Loves music, mornings, literature, yoga, nature, people and silence.",
  "Benches and birds makes me happy.",
  'Life is a journey, not a race" -Bonnie Mohr- Sinivalkoinen sydämeni sykkii vahvasti Suomelle ja turvallisuudelle.',
  "Digitalist.",
  "Visualist.",
  "Really passionate about customers and developing the amazing customer experiences with the modern technologies for marketing, sales and customer care.",
  "I’m really passionate about helping customers to make even more profitable business in digital channels, serving their customer in an omni-channel environment, modernizing their marketing and developing their sales processes.",
  "I’m a marketing believer.",
  "Specialties: Key skills include strategic analysis and coaching multi-disciplinary teams I'm an enthusiastic Lean & Lean Startup Coach on a mission to re-build company cultures with believing in people and their passion.",
  "Eager to drive organisational/cultural change and renewal - also learning to listen more and talk less.",
  "Intohimona kehittäminen ja kehittyminen.",
  "#asiakaskokemus #sisältömarkkinointi ##NAME## is an award-winning designer & creative director.",
  "Viimeiset viisi vuotta hän on pohtinut onnellisen asiakkaan dilemmaa: mitä tietoa, analyysiratkaisuja ja prosesseja tarvitaan asiakaskokemuksen parantamiseen.",
  "Commerce professional in omni-channel world.",
  "Proven track record on developing successful multi-channel strategies for media, b2b and retail companies.",
  "Public speaker on the subject.",
  "Entrepreneur able to execute.",
  "Special interest and deep know-how in new business models, e-commerce and internet technologies in very broad spectrum.",
  "Always focused on strategy creation, business development and growth tactics.",
  "Viestinnän digitaalisuus ja sähköisyys ei mielestäni rajoitu vain virtaa käyttäviin päätelaitteisiin.",
  "Se on asennetta ja luovuutta löytää keinot puhutella yleisöä kohdennetusti oikealla hetkellä.",
  "Passionately curious entrepreneur who loves to be around exceptional people solving meaningful global problems.",
  "Matkabloggaaja, free-toimittaja ja -kuvaaja, joka on puhunut kutsuvieraana matkailusta ja matkabloggaamisesta, ja tehnyt blogimatkoja yhteistyössä eri matkajärjestäjien kanssa Suomen Turusta Euroopan kautta Singaporeen.",
  "Takana lähes 20-vuotta kuluttaja- ja asiakaskeskeistä tekemistä - tutkimusta, liiketoiminnan kehitystä sekä asiakaskokemuksen näkyväksi tekemistä.",
  "Vannoo edelleen osallistavan toimintakulttuurin, siilojen purkamisen sekä lapsenomaisen uteliaisuuden ja kokeilunhalun nimeen.",
  "I learned how effective and inspiring the teamwork can be when everything is new and changing every day.",
  "Thats why it´s really inspiring when the era of Branded Content has started.",
  "##NAME## on liiketoiminnan kehittäjä ja vuokrajohtaja.",
  "Korkean teknologian hankkeet ja kansainvälinen toiminta sydäntä lähellä.",
  "Intohimona markkinointi.",
  "15 vuoden kokemus myynnin ja markkinoinnin johtotehtävistä"
]